### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by tehseensagar** [invasi0nZ/Lo0sR#1]
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    from SimpleCV import Camera
  File "C:\Python27\lib\site-packages\SimpleCV\__init__.py", line 3, in <module>

    from SimpleCV.base import *
  File "C:\Python27\lib\site-packages\SimpleCV\base.py", line 59, in <module>
    raise ImportError("Cannot load OpenCV library which is required by SimpleCV"
)
ImportError: Cannot load OpenCV library which is required by SimpleCV

**Comment by invasi0nZ** [comment]
Do you have OpenCV?

**Comment by tehseensagar** [comment]
I do have it, I installed it via pip install OpenCV .  Blow are the steps I did.

pip install opencv-python
pip install SimpleCV
python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose pygame
